In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
torch.__version__

'2.2.0+cpu'

In [5]:
scalar = torch.tensor(5)
scalar

tensor(5)

In [7]:
vector = torch.tensor([2,2])
vector

tensor([2, 2])

In [8]:
scalar.ndim

0

In [13]:
scalar.item()

5

In [14]:
MATRIX = torch.tensor([[2,2],
                       [5,6]])
MATRIX

tensor([[2, 2],
        [5, 6]])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
rand_ten = torch.rand(1,5,2)
rand_ten

tensor([[[0.8426, 0.2787],
         [0.8526, 0.4298],
         [0.6523, 0.3875],
         [0.3766, 0.5602],
         [0.4413, 0.2307]]])

In [17]:
rand_ten.ndim

2

In [26]:
random_img_tensor = torch.rand(size =(3,224,224))
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [28]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
flot_tensor = torch.tensor([3,6,8], dtype = torch.float16, device=None, requires_grad=False)

In [48]:
flot_tensor.dtype

torch.float16

In [78]:
eg = torch.rand(3,2)

In [51]:
eg + 100

tensor([101, 102, 103])

In [52]:
eg*5

tensor([ 5, 10, 15])

In [55]:
torch.mul(eg,5)

tensor([ 5, 10, 15])

In [56]:
torch.matmul(eg,eg)

tensor(14)

In [58]:
time_test = torch.rand(10000,10000)
time_test

tensor([[0.7153, 0.6154, 0.1915,  ..., 0.1283, 0.0174, 0.9603],
        [0.1548, 0.4820, 0.4823,  ..., 0.4321, 0.0727, 0.5273],
        [0.7002, 0.9229, 0.3690,  ..., 0.1062, 0.0676, 0.8841],
        ...,
        [0.8166, 0.2055, 0.9421,  ..., 0.3382, 0.4546, 0.3855],
        [0.2675, 0.5012, 0.4125,  ..., 0.6250, 0.8894, 0.1060],
        [0.2467, 0.7259, 0.3051,  ..., 0.8994, 0.3162, 0.2729]])

In [67]:
%%time
value = 0
for i in range(len(time_test)):
  value += time_test[i] * time_test[i]
print(value)

tensor([3325.5151, 3322.9883, 3332.6250,  ..., 3317.7661, 3290.5984,
        3374.8196])
CPU times: total: 31.2 ms
Wall time: 76 ms


In [70]:
%%time
torch.matmul(eg,eg)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [79]:
eg

tensor([[0.8866, 0.5510],
        [0.5686, 0.6480],
        [0.1309, 0.3785]])

In [80]:
eg.T

tensor([[0.8866, 0.5686, 0.1309],
        [0.5510, 0.6480, 0.3785]])

In [82]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
torch.min(x)

tensor(0)

In [85]:
x.min()

tensor(0)

In [86]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [87]:
torch.sum(x)

tensor(450)

In [88]:
a = torch.tensor([5,4,6,8,9,6,2,1])
a

tensor([5, 4, 6, 8, 9, 6, 2, 1])

In [89]:
a.argmin()

tensor(7)

In [90]:
a[7]

tensor(1)

In [91]:
a.argmax()

tensor(4)

In [115]:
t = torch.arange(1.,10.)
t, t.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [109]:
t_reshaped = t.reshape(9,1)
t_reshaped, t_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [110]:
p = t.view(1,9)
p, p.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [111]:
p

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [113]:
p[:, 0] = 9
p, t

(tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([9., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [117]:
t_stacked = torch.stack([t,t,t], dim = 1)
t_stacked

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [118]:
index_tensor = torch.arange(1,10).reshape(1,3,3)
index_tensor, index_tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [119]:
index_tensor[0,1]

tensor([4, 5, 6])

In [120]:
index_tensor[0,2,2]

tensor(9)

In [125]:
index_tensor[:, :, 0]

tensor([[1, 4, 7]])

In [165]:
array = np.arange(1, 8)
tensor = torch.from_numpy(array).type(torch.float32)

In [130]:
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [166]:
array+=1
array, tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [177]:
torch.rand(3,3)

tensor([[0.2076, 0.7931, 0.8145],
        [0.4275, 0.6275, 0.8237],
        [0.8505, 0.9237, 0.5851]])

In [182]:
tensor_A = torch.rand(3,3)
tensor_B = torch.rand(3,3)
tensor_A == tensor_B

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [184]:
RANDOM_SEED = 42


In [186]:
torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(3,3)
torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(3,3)
tensor_C == tensor_D

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])